# Generated by Django 4.2.15 on 2024-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Task Category', 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
