# Generated by Django 4.2.15 on 2024-08-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('task', '0002_alter_task_options_alter_taskcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_performer', to='user_profile.userprofile'),
        ),
    ]
