# Generated by Django 4.2.15 on 2024-08-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_verification_remarks'),
        ('task', '0004_alter_task_status_alter_task_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_rate', models.IntegerField(default=0)),
                ('provider_feedback', models.TextField(blank=True, null=True)),
                ('performer_rate', models.IntegerField(default=0)),
                ('performer_feedback', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_review', to='task.task')),
            ],
            options={
                'verbose_name': 'Task Review',
                'verbose_name_plural': 'Task Review',
            },
        ),
        migrations.CreateModel(
            name='TaskApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_applicant_performer', to='user_profile.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_applicant', to='task.task')),
            ],
            options={
                'verbose_name': 'Task Applicant',
                'verbose_name_plural': 'Task Applicants',
                'unique_together': {('task', 'performer')},
            },
        ),
    ]
