# Generated by Django 4.2.15 on 2024-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskreview_taskapplicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskapplicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='taskreview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
        migrations.AlterField(
            model_name='taskapplicant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
