# Generated by Django 4.2.15 on 2024-08-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
