# Generated by Django 4.2.15 on 2024-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_latitude_alter_task_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
