# Generated by Django 4.2.15 on 2024-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_task_is_done_perform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ['-updated_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
