# Generated by Django 4.2.15 on 2024-09-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_task_options_alter_task_schedule_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
