# Generated by Django 4.2.15 on 2024-09-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_taskcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskapplicant',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_review', to='task.task'),
        ),
    ]
