# Generated by Django 4.2.15 on 2024-09-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_taskreview_performer_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskreview',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
    ]
