# Generated by Django 4.2.15 on 2024-08-20 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('verification_status', models.CharField(choices=[('PROCESSING_APPLICATION', 'PROCESSING APPLICATION'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('N/A', 'N/A')], default='N/A', max_length=100)),
                ('verification_remarks', models.TextField(null=True)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='images/ids/')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='images/faces/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
