# Generated by Django 4.2.13 on 2024-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
